package agent

import (
	"path/filepath"
	"strings"
)

// runtimeArtifactPath identifies files generated by Ephemera itself while a
// run is active. They remain visible in diagnostics and git status, but they do
// not belong to the user's task diff and must never block task completion.
func runtimeArtifactPath(path string) bool {
	path = normalizePath(path)
	if path == "" {
		return false
	}
	base := strings.ToLower(filepath.Base(filepath.FromSlash(path)))
	if strings.HasPrefix(path, ".ephemera/") || path == ".ephemera" {
		relative := strings.TrimPrefix(strings.TrimPrefix(path, ".ephemera"), "/")
		first := relative
		if index := strings.IndexByte(first, '/'); index >= 0 {
			first = first[:index]
		}
		switch strings.ToLower(first) {
		case "cache", "logs", "sessions", "tmp", "worktrees":
			return true
		}
		switch strings.ToLower(relative) {
		case "metrics.json", "memory.json", "codebase-index.json", "run.sh", "run.ps1", "run.bat", "run.cmd":
			return true
		}
		if strings.HasPrefix(strings.ToLower(relative), "run-") &&
			(strings.HasSuffix(base, ".sh") || strings.HasSuffix(base, ".ps1") || strings.HasSuffix(base, ".bat") || strings.HasSuffix(base, ".cmd")) {
			return true
		}
	}
	return false
}

func (s *runState) recordChangedArtifact(path string, directory bool) {
	if s == nil {
		return
	}
	path = normalizePath(path)
	if path == "" {
		return
	}
	if runtimeArtifactPath(path) {
		if s.runtimeChangedPaths == nil {
			s.runtimeChangedPaths = map[string]bool{}
		}
		s.runtimeChangedPaths[path] = true
		return
	}
	s.changed = true
	s.verified = false
	if directory {
		if s.changedDirectories == nil {
			s.changedDirectories = map[string]bool{}
		}
		s.changedDirectories[path] = true
		return
	}
	if s.changedPaths == nil {
		s.changedPaths = map[string]bool{}
	}
	s.changedPaths[path] = true
}

func runtimeChangedArtifactPaths(state *runState) []string {
	if state == nil {
		return nil
	}
	return sortedKeys(state.runtimeChangedPaths)
}
